apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: yn-spring-sensors
  description: Spring Sensors
  tags:
    - app-accelerator
    - java
    - spring
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=spring-sensors-rabbit'
spec:
  type: service
  lifecycle: experimental
  owner: penske-team
