apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: yn-spring-sensors
  namespace: dev-ns
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: yn-spring-sensors
spec:
  source:
    git:
      url: https://github.com/ynamadi/spring-sensors-rabbit.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1